### ISSUE TITLE
Syntax error: "(" unexpected

### ISSUE THREAD

**Issue by SamuDifferent** [itsfolf/Discord-Screenshare-Linux#10]
When i try to run the install-script i get this error message "Syntax error: "(" unexpected
"

**Comment by Growebis** [comment]
im also having the same issue

**Comment by willgvfranco** [comment]
Try to use the follow command:
`bash -c "$(curl https://raw.githubusercontent.com/fuwwy/Discord-Screenshare-Linux/main/scripts/install.sh -sSfL)"`

**Comment by ToasterUwU** [comment]
Same issue here, i rewrote the command and that new command works and does the exact same thing. Feel free to use it:

```
wget -q -O - "https://raw.githubusercontent.com/fuwwy/Discord-Screenshare-Linux/main/scripts/install.sh" | bash
```

**Comment by itsfolf** [comment]
My guess is this has something to do with sh, should I change the readme to use bash instead?

**Comment by ToasterUwU** [comment]
> My guess is this has something to do with sh, should I change the readme to use bash instead?

Yes, i just tested it. Replacing sh with bash for the install command does exactly what you/we want it to do. While sh just errors out.
